package com.vantage.dialer.api.dto;

public record CustomerConfigurationResponse(
        String customerId,
        String customerName,
        String serverAHost,
        String serverAPrivateIp,
        String serverBHost,
        String asteriskDeployUser,
        String asteriskDeployPrivateKeyPath,
        String asteriskDeployTargetDirectory,
        String amiUsername,
        String amiEndpoint,
        String dialPrefix,
        String sipDomain,
        String webSocketUrl,
        String apiBaseUrl,
        String defaultAgentUiMode,
        String defaultSupervisorUiMode,
        String brandDisplayName,
        String brandLogoUrl,
        String brandPrimaryColor,
        String brandAccentColor,
        String proposalPreset,
        String proposalTemplate,
        String proposalTitle,
        String proposalSubtitle,
        Boolean proposalIncludeAgentOutbound,
        Boolean proposalIncludeIvr,
        Boolean proposalIncludeReporting,
        Boolean proposalIncludeWebRtc,
        Boolean proposalIncludeProvisioning,
        Boolean proposalIncludePricingBreakdown,
        Long defaultMonthlyCallMinutes,
        Long defaultMonthlyTtsUnits,
        Long defaultMonthlySttMinutes,
        Double defaultMonthlyRecordingGb,
        Integer defaultAgentCount,
        Integer defaultConcurrentChannels,
        Double defaultMarginPercent,
        String proposalTerms) {
}
